apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local:9090   # Use the internal service name to access Prometheus
        isDefault: true
        version: 1
        editable: true
