apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-api-deployment
  labels:
    app: movie-analyst-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-analyst-api
  template:
    metadata:
      labels:
        app: movie-analyst-api
      annotations:                            
        prometheus.io/scrape: "true"         
        prometheus.io/path: "/metrics"       
    spec:
      containers:
        - name: movie-analyst-api
          image: {{ .Values.api.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: {{ .Values.DB_HOST.name }}
            - name: DB_USER
              value: {{ .Values.DB_USER.name }}
            - name: DB_PASS
              value: {{ .Values.DB_PASS.pass }}
            - name: DB_NAME
              value: {{ .Values.DB_NAME.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-analyst-api-service
spec:
  selector:
    app: movie-analyst-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30301