ui:
  image: leandroid/movie-analyst-ui

monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true

ingress:
  hosts:
    - host: movie-analyst-ui.info
      paths:
        - path: /
          pathType: Prefix

ingressPort: 3000