{{- $ingressPort := .Values.ingressPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-analyst-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http: 
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: movie-analyst-ui-service
                port:
                  number: {{ $ingressPort }}
            {{- end }}
      {{- end }}